# Generated by Django 5.2.7 on 2025-10-31 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('estatura', models.FloatField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
    ]
