# Generated by Django 5.2.7 on 2025-10-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
