# Generated by Django 5.2.7 on 2025-11-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_rename_usuario_id_perfil_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False},
        ),
    ]
