# Generated by Django 5.2.7 on 2025-11-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_auto_20251104_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
