# Generated by Django 5.2.7 on 2025-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_auto_20251104_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
