# Generated by Django 5.2.7 on 2025-11-04 05:52

import apps.profile_app.subapps.imageUpload.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=apps.profile_app.subapps.imageUpload.models.user_directory_path)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de Perfil',
                'verbose_name_plural': 'Imagenes de Perfil',
                'db_table': 'imagen',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
