# Generated by Django 5.2.7 on 2025-11-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rango_edad_min', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_edad_max', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_estatura_min', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_estatura_max', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('genero_preferido', models.CharField(blank=True, max_length=50, null=True)),
                ('hobbies_preferidos', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_types', models.JSONField(default=list)),
                ('filter_values', models.JSONField(default=list)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='preferences_app.preference')),
            ],
        ),
    ]
