# Generated by Django 5.2.7 on 2025-10-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario (proxy)',
                'verbose_name_plural': 'Usuarios (proxy)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('legacy_models.usuario',),
        ),
    ]
