# Generated by Django 5.2.7 on 2025-10-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='ubicacion',
        ),
    ]
