# Generated by Django 5.2.7 on 2025-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_genero_table_alter_programa_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apodo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechanacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numerotelefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
