# Generated by Django 5.2.7 on 2025-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_usuario_apodo_alter_usuario_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estadocuenta',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
