# Generated by Django 5.2.7 on 2025-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_usuario_estadocuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apodo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estatura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='filtros',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='gustos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagen_principal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='likes',
        ),
    ]
