# Generated by Django 5.2.7 on 2025-10-31 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_usuario_apodo_remove_usuario_estatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
