# Generated by Django 5.2.7 on 2025-10-31 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_ubicacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
