# Generated by Django 5.2.7 on 2025-10-31 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_programa_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
