# Generated by Django 5.2.7 on 2025-10-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genero',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('orientacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orientacion',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programa',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestresubicacion',
            fields=[
                ('semestreubicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'semestresubicacion',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('ubicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ubicacion',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechanacimiento', models.DateField()),
                ('email', models.CharField(max_length=60, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('apodo', models.CharField(max_length=50)),
                ('numerotelefono', models.CharField(max_length=15)),
                ('imagen_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('gustos', models.CharField(blank=True, max_length=255, null=True)),
                ('estatura', models.FloatField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('filtros', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('estadocuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('tyc', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('verificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaexpiracion', models.DateTimeField()),
                ('usado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verificacion',
                #'managed': False,
            },
        ),
    ]
