# Generated by Django 5.2.7 on 2025-10-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orientacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semestresubicacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificacion',
            options={},
        ),
    ]
